Algoritmo "Meu prieiro algoritimo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/09/2021
Var
// Seção de Declarações das variáveis
   Nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Nota <-100
   escreva("resultado", nota)

Fimalgoritmo